[package]
name = "eu4_bevy"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
    "crates/*", # this one has small utilites like asset packer that copies all assets from eu4 into one tar file
]

[features]
dynamic = ["bevy/dynamic_linking"]
debug = ["bevy/debug"]

[dependencies]
bevy = { version = "0.19.1", features = ["dds","wav","bevy_dev_tools"] }
log = { version = "*", features = ["max_level_debug", "release_max_level_warn"] }
serde = { version = "*", features = ["derive"] }
serde_json = { version = "*" }
settings = { path = "crates/settings" }
fonts = { path = "crates/fonts" }
rand = "0.10.2"
bevy_fluent = { version = "0.15.0" }
unic-langid = {version = "0.9.0", features = ["macros"]}
fluent_content = "0.0.5"
path-clean  = "1.0.1"


# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3


# Enable more optimization in the release profile at the cost of compile time.
[profile.release]
# Compile the entire crate as one unit.
# Slows compile times, marginal improvements.
# codegen-units = 1
# Do a second optimization pass over the entire program, including dependencies.
# Slows compile times, marginal improvements.
# lto = "thin"

# Optimize for size in the wasm-release profile to reduce load times and bandwidth usage on web.
[profile.wasm-release]
# Default to release profile values.
inherits = "release"
# Optimize with size in mind (also try "z", sometimes it is better).
# Slightly slows compile times, great improvements to file size and runtime performance.
opt-level = "s"
# Strip all debugging information from the binary to slightly reduce file size.
strip = "debuginfo"
